from typing import Any

def normalize_place_batch(records: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
def distance_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float: ...
def validate_nearby_request(place_id: str, radius_m: float, limit: int, preference: str) -> None: ...
def validate_page(limit: int, offset: int) -> None: ...
